{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<script src={"javascript/yahoo/yahoo-min.js"|ezdesign}></script>
<script src={"javascript/event/event-min.js"|ezdesign}></script>
<script src={"javascript/treeview/treeview.js"|ezdesign}></script>
<script src={"javascript/eztreeselection.js"|ezdesign}></script>

<div class="block">
<label>{'Type'|i18n( 'design/standard/class/datatype' )}:</label>
    {section show=$class_attribute..content.is_multiselect}
        <p>{'Multiple choice'|i18n( 'design/standard/class/datatype' )}</p>
    {section-else}
        <p>{'Single choice'|i18n( 'design/standard/class/datatype' )}</p>
    {/section}
</div>

<div class="block">
<div id="ContentClass_eztreeselection_main_{$class_attribute.id}">
<script type="text/javascript">
	{$class_attribute.content.classViewYuiTreeViewJavascript}
</script>
</div>
</div>
