{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<script src={"javascript/yahoo/yahoo-min.js"|ezdesign}></script>
<script src={"javascript/event/event-min.js"|ezdesign}></script>
<script src={"javascript/treeview/treeview.js"|ezdesign}></script>
<script src={"javascript/eztreeselection.js"|ezdesign}></script>
{default attribute_base=ContentObjectAttribute}

<div id="{$attribute_base}_eztreeselection_main_{$attribute.id}">
<script type="text/javascript">
	{$attribute.content.contentEditYuiTreeViewJavascript}
</script>
</div>

{/default}
