{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}

<div id="{$attribute_base}_eztreeselection_main_{$attribute.id}">
<script type="text/javascript">
	{$attribute.content.contentEditYuiTreeViewJavascript}
</script>
</div>

{/default}
